version: '3.8'

services:
    example_app:
        build:
            dockerfile: Dockerfile
        image: example_project
        container_name: laravel_app
        working_dir: /var/www/example
        volumes:
            - .:/var/www/example
        depends_on:
            - mysql
            - redis

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_ROOT_PASSWORD: root-password
            MYSQL_USER: laravel-user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root-password
        ports:
            - "8081:80"
        depends_on:
            - mysql

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    webserver:
        image: nginx:alpine
        container_name: nginx_webserver
        volumes:
            - .:/var/www/example
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - example_app

volumes:
    db_data:
    redis_data:
